# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
profile = "custom"
[msbuild]
project = "BB84.Extensions.sln"
[github]
user = "BoBoBaSs84"
repo = "BB84.Extensions"
[nuget]
publish = true
source = "https://api.nuget.org/v3/index.json"
publish_draft = true
