# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
profile = "custom"
[msbuild]
project = "BB84.Extensions.sln"
[github]
user = "BoBoBaSs84"
repo = "BB84.Extensions"
version_prefix = "v"
[nuget]
publish = true
